# ====== BUILD STAGE (MAVEN + JAVA 25) ======
FROM azul/zulu-openjdk:25 AS build
WORKDIR /app

# Install Maven
RUN apt-get update && apt-get install -y maven

# Copy pom.xml and download dependencies
COPY pom.xml .
RUN mvn dependency:go-offline

# Copy project source
COPY src ./src

# Build Spring Boot application
RUN mvn clean package -DskipTests


# ====== RUNTIME STAGE (JAVA 25 JDK) ======
FROM azul/zulu-openjdk:25
WORKDIR /app

# Copy built JAR from build stage
COPY --from=build /app/target/*.jar app.jar

# Expose Spring Boot port
EXPOSE 8080

# Run jar
ENTRYPOINT ["java", "-jar", "app.jar"]
